---

- name: Create export directory
  when: inventory_hostname in groups['storage_nodes']
  ansible.builtin.file:
    path: "{{ nfs_dir_path }}"
    state: directory
    mode: 0777

- name: Set export
  when: inventory_hostname in groups['storage_nodes']
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_dir_path}} *(rw)"

- name: Set static nfs ports
  when: inventory_hostname in groups['storage_nodes']
  lineinfile:
    path: /etc/default/nfs-kernel-server
    regex: '^RPCMOUNTDOPTS=.*$'
    line: "RPCMOUNTDOPTS=\"-p {{ nfs_rpc_mountd_port }}\""

- name: Set static nfs-common port
  when: inventory_hostname in groups['storage_nodes']
  lineinfile:
    path: /etc/default/nfs-common
    regex: '^STATDOPTS=.*$'
    line: "STATDOPTS=\"--port {{ nfs_common_port }} --outgoing-port {{ nfs_common_outgoing_port }}\""
  notify: Ensure services on nfs server

- name: Setup NFS clients mount point
  when: inventory_hostname not in groups['storage_nodes']
  ansible.builtin.file:
    path: "{{ nfs_client_dir_path }}"
    state: directory
  notify: Ensure services on nfs client

- name: Mount NFS server on clients
  when: inventory_hostname not in groups['storage_nodes']
  ansible.posix.mount:
    src: "{{ hostvars[groups['storage_nodes'][0]].ansible_host }}:{{ nfs_dir_path }}"
    path: "{{ nfs_client_dir_path }}"
    opts: defaults
    state: mounted
    fstype: nfs
