---

- name: setup ufw for NFS
  when: inventory_hostname in groups['storage_nodes']
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: "192.168.2.0/24"
  loop:
    - { port: '{{ nfs_ports }}', proto: 'tcp' }
    - { port: '{{ nfs_ports }}', proto: 'udp' }
    - { port: '111', proto: 'any'}
    - { port: '2049', proto: 'any'}
