---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "openldap"
  name: "openldap-storage"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "50Gi"
