---

storage_packages:
  - lvm2
  - nfs-common
  - nfs-kernel-server

k3s_vgroup:
  vg_name: "vg_k3s"
  vg_pvs:
    - "/dev/sda"
  lv_name: "lv_k3s_nfs"
  lv_size: "200G"
  fs_type: "ext4"
  fs_mount: "/srv/k3s_nfs"

nfs_dir_path: "/srv/k3s_nfs"
