---

- hosts: all
  gather_facts: yes
  become: yes
  roles:
#    - role: storage/rockpi_sata_hat
      #    - role: storage/disk_formatting
    - role: storage/lvm
      hosts: storage_nodes

    - role: storage/nfs
