---

- name: Create export directory
  when: inventory_hostname in groups['storage_nodes']
  ansible.builtin.file:
    path: "{{ nfs_dir_path }}"
    state: directory
    mode: 0777

- name: Set export
  when: inventory_hostname in groups['storage_nodes']
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_dir_path}} *(rw)"

- name: Start NFS services
  when: inventory_hostname in groups['storage_nodes']
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    state: restarted
    enabled: yes
  loop:
    - rpcbind
    - rpc-statd
    - nfs-idmapd
    - nfs-server
