---

- name: Create export directory
  when: inventory_hostname in groups['storage_nodes']
  ansible.builtin.file:
    path: "{{ nfs_dir_path }}"
    state: directory
    mode: 0777

- name: Set export
  when: inventory_hostname in groups['storage_nodes']
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_dir_path}} *(rw)"

- name: Set static NFS Port
  when: inventory_hostname in groups['storage_nodes']
  lineinfile:
    path: /etc/default/nfs-kernel-server
    reges: '^RPCMOUNTDOPTS=.*$'
    line: "-p {{ nfs_port }}"

# TODO export to Handler
- name: Start NFS services
  when: inventory_hostname in groups['storage_nodes']
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    state: restarted
    enabled: yes
  loop:
    - rpcbind
    - rpc-statd
    - nfs-idmapd
    - nfs-server

- name: Setup NFS clients mount point
  when: inventory_hostname not in groups['storage_nodes']
  ansible.builtin.file:
    path: "{{ nfs_client_dir_path }}"
    state: directory

- name: Start NFS services on clients
  when: inventory_hostname not in groups['storage_nodes']
  systemd:
    name: "rpcbind"
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Mount NFS server on clients
  when: inventory_hostname not in groups['storage_nodes']
  ansible.posix.mount:
    src: "{{ hostvars[groups['storage_nodes'][0]].ansible_host }}:{{ nfs_dir_path }}"
    path: "{{ nfs_client_dir_path }}"
    opts: rw,sync,hard,int
    state: mounted
    fstype: nfs
