---

- name: include os specific vars
  include_vars: '{{ item  }}'
  with_first_found:
      - '{{ ansible_distribution }}.yml'
      - 'main.yml'
  
- name: install base packages
  tags:
      - packages
  import_tasks: packages.yml

- name: configure users
  tags:
      - users
  include: users.yml

- name: security configurations
  tags:
      - security
  include: security.yml
